name: Compile/Test

on:
  push:
    branches-ignore:
      - main

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
          
      # Clear Foundry Cache (this clears the global cache, ensuring no conflicts)
      - name: Clear Foundry Cache
        run: forge clean

      # Install Foundry Dependencies (including forge-std)
      - name: Install Foundry Dependencies
        run: |
          forge install
          echo "Listing lib directory after install:"
          ls -la lib
          echo "Listing forge-std directory:"
          ls -la lib/forge-std

      # Debug: Print out the contents of the 'lib' directory to verify that dependencies were installed
      - name: List Foundry lib directory
        run: ls -R lib

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
      - run: yarn run test
      - run: yarn run fuzz
